mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taotao
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource


dubbo:
  application:
    name: taotao-manager
  registry:
    address: zookeeper://192.254.64.128:2181
  scan:
    basePackages: com.yk.service
  protocol:
    port: 20882